- type: FILE
  space: "<SPACE_NAME>"
  config:
    path: "./seeds/tenants/musterkmu/docs"
- type: WEBSITE
  space: "<SPACE_NAME>"
  config:
    url: "https://www.example.org/musterkmu/"
    crawl: { sitemap: false, depth: 1 }
